package entities;
// Generated Apr 15, 2018 3:12:47 PM by Hibernate Tools 4.3.1



/**
 * Food generated by hbm2java
 */
public class Food  implements java.io.Serializable {


     private int foodId;
     private int foodCategoryId;
     private String foodVName;
     private String foodEName;
     private String foodUses;
     private String foodImage;
     private String water;
     private String energy;
     private String protein;
     private String lipid;
     private String carbohydrate;
     private String celluloza;
     private String tro;
     private String sugar;
     private String calcium;
     private String iron;
     private String magnesium;
     private String manganese;
     private String phosphorous;
     private String potassium;
     private String sodium;
     private String zinc;
     private String copper;
     private String selenium;
     private String vitaminC;
     private String vitaminB1;
     private String vitaminB2;
     private String vitaminPp;
     private String vitaminB5;
     private String vitaminB6;
     private String folat;
     private String vitaminB9;
     private String vitaminH;
     private String vitaminB12;
     private String vitaminA;
     private String vitaminD;
     private String vitaminE;
     private String vitaminK;
     private String betaCaroten;
     private String alphaCaroten;
     private String betaCryptoxanthin;
     private String lypcogen;
     private String lycopen;
     private String lutein;
     private String purin;
     private String totalIsoflavone;
     private String totalSFAcid;
     private String totalMFAcid;
     private String totalPFAcid;
     private String totalTFAcid;
     private Integer cholesterol;
     private Integer phytosterol;
     private Integer lysin;
     private Integer methionin;
     private Integer tryptophan;
     private Integer phenylalanin;
     private Integer threonin;
     private Integer valin;
     private Integer leucin;
     private Integer isoleucin;
     private Integer arginin;
     private Integer histidin;
     private Integer cystin;
     private Integer tyrosin;
     private Integer alanin;
     private Integer acidAspartic;
     private Integer acidGlutamic;
     private Integer glycin;
     private Integer prolin;
     private Integer serin;

    public Food() {
    }

	
    public Food(int foodId, int foodCategoryId) {
        this.foodId = foodId;
        this.foodCategoryId = foodCategoryId;
    }
    public Food(int foodId, int foodCategoryId, String foodVName, String foodEName, String foodUses, String foodImage, String water, String energy, String protein, String lipid, String carbohydrate, String celluloza, String tro, String sugar, String calcium, String iron, String magnesium, String manganese, String phosphorous, String potassium, String sodium, String zinc, String copper, String selenium, String vitaminC, String vitaminB1, String vitaminB2, String vitaminPp, String vitaminB5, String vitaminB6, String folat, String vitaminB9, String vitaminH, String vitaminB12, String vitaminA, String vitaminD, String vitaminE, String vitaminK, String betaCaroten, String alphaCaroten, String betaCryptoxanthin, String lypcogen, String lycopen, String lutein, String purin, String totalIsoflavone, String totalSFAcid, String totalMFAcid, String totalPFAcid, String totalTFAcid, Integer cholesterol, Integer phytosterol, Integer lysin, Integer methionin, Integer tryptophan, Integer phenylalanin, Integer threonin, Integer valin, Integer leucin, Integer isoleucin, Integer arginin, Integer histidin, Integer cystin, Integer tyrosin, Integer alanin, Integer acidAspartic, Integer acidGlutamic, Integer glycin, Integer prolin, Integer serin) {
       this.foodId = foodId;
       this.foodCategoryId = foodCategoryId;
       this.foodVName = foodVName;
       this.foodEName = foodEName;
       this.foodUses = foodUses;
       this.foodImage = foodImage;
       this.water = water;
       this.energy = energy;
       this.protein = protein;
       this.lipid = lipid;
       this.carbohydrate = carbohydrate;
       this.celluloza = celluloza;
       this.tro = tro;
       this.sugar = sugar;
       this.calcium = calcium;
       this.iron = iron;
       this.magnesium = magnesium;
       this.manganese = manganese;
       this.phosphorous = phosphorous;
       this.potassium = potassium;
       this.sodium = sodium;
       this.zinc = zinc;
       this.copper = copper;
       this.selenium = selenium;
       this.vitaminC = vitaminC;
       this.vitaminB1 = vitaminB1;
       this.vitaminB2 = vitaminB2;
       this.vitaminPp = vitaminPp;
       this.vitaminB5 = vitaminB5;
       this.vitaminB6 = vitaminB6;
       this.folat = folat;
       this.vitaminB9 = vitaminB9;
       this.vitaminH = vitaminH;
       this.vitaminB12 = vitaminB12;
       this.vitaminA = vitaminA;
       this.vitaminD = vitaminD;
       this.vitaminE = vitaminE;
       this.vitaminK = vitaminK;
       this.betaCaroten = betaCaroten;
       this.alphaCaroten = alphaCaroten;
       this.betaCryptoxanthin = betaCryptoxanthin;
       this.lypcogen = lypcogen;
       this.lycopen = lycopen;
       this.lutein = lutein;
       this.purin = purin;
       this.totalIsoflavone = totalIsoflavone;
       this.totalSFAcid = totalSFAcid;
       this.totalMFAcid = totalMFAcid;
       this.totalPFAcid = totalPFAcid;
       this.totalTFAcid = totalTFAcid;
       this.cholesterol = cholesterol;
       this.phytosterol = phytosterol;
       this.lysin = lysin;
       this.methionin = methionin;
       this.tryptophan = tryptophan;
       this.phenylalanin = phenylalanin;
       this.threonin = threonin;
       this.valin = valin;
       this.leucin = leucin;
       this.isoleucin = isoleucin;
       this.arginin = arginin;
       this.histidin = histidin;
       this.cystin = cystin;
       this.tyrosin = tyrosin;
       this.alanin = alanin;
       this.acidAspartic = acidAspartic;
       this.acidGlutamic = acidGlutamic;
       this.glycin = glycin;
       this.prolin = prolin;
       this.serin = serin;
    }
   
    public int getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }
    public int getFoodCategoryId() {
        return this.foodCategoryId;
    }
    
    public void setFoodCategoryId(int foodCategoryId) {
        this.foodCategoryId = foodCategoryId;
    }
    public String getFoodVName() {
        return this.foodVName;
    }
    
    public void setFoodVName(String foodVName) {
        this.foodVName = foodVName;
    }
    public String getFoodEName() {
        return this.foodEName;
    }
    
    public void setFoodEName(String foodEName) {
        this.foodEName = foodEName;
    }
    public String getFoodUses() {
        return this.foodUses;
    }
    
    public void setFoodUses(String foodUses) {
        this.foodUses = foodUses;
    }
    public String getFoodImage() {
        return this.foodImage;
    }
    
    public void setFoodImage(String foodImage) {
        this.foodImage = foodImage;
    }
    public String getWater() {
        return this.water;
    }
    
    public void setWater(String water) {
        this.water = water;
    }
    public String getEnergy() {
        return this.energy;
    }
    
    public void setEnergy(String energy) {
        this.energy = energy;
    }
    public String getProtein() {
        return this.protein;
    }
    
    public void setProtein(String protein) {
        this.protein = protein;
    }
    public String getLipid() {
        return this.lipid;
    }
    
    public void setLipid(String lipid) {
        this.lipid = lipid;
    }
    public String getCarbohydrate() {
        return this.carbohydrate;
    }
    
    public void setCarbohydrate(String carbohydrate) {
        this.carbohydrate = carbohydrate;
    }
    public String getCelluloza() {
        return this.celluloza;
    }
    
    public void setCelluloza(String celluloza) {
        this.celluloza = celluloza;
    }
    public String getTro() {
        return this.tro;
    }
    
    public void setTro(String tro) {
        this.tro = tro;
    }
    public String getSugar() {
        return this.sugar;
    }
    
    public void setSugar(String sugar) {
        this.sugar = sugar;
    }
    public String getCalcium() {
        return this.calcium;
    }
    
    public void setCalcium(String calcium) {
        this.calcium = calcium;
    }
    public String getIron() {
        return this.iron;
    }
    
    public void setIron(String iron) {
        this.iron = iron;
    }
    public String getMagnesium() {
        return this.magnesium;
    }
    
    public void setMagnesium(String magnesium) {
        this.magnesium = magnesium;
    }
    public String getManganese() {
        return this.manganese;
    }
    
    public void setManganese(String manganese) {
        this.manganese = manganese;
    }
    public String getPhosphorous() {
        return this.phosphorous;
    }
    
    public void setPhosphorous(String phosphorous) {
        this.phosphorous = phosphorous;
    }
    public String getPotassium() {
        return this.potassium;
    }
    
    public void setPotassium(String potassium) {
        this.potassium = potassium;
    }
    public String getSodium() {
        return this.sodium;
    }
    
    public void setSodium(String sodium) {
        this.sodium = sodium;
    }
    public String getZinc() {
        return this.zinc;
    }
    
    public void setZinc(String zinc) {
        this.zinc = zinc;
    }
    public String getCopper() {
        return this.copper;
    }
    
    public void setCopper(String copper) {
        this.copper = copper;
    }
    public String getSelenium() {
        return this.selenium;
    }
    
    public void setSelenium(String selenium) {
        this.selenium = selenium;
    }
    public String getVitaminC() {
        return this.vitaminC;
    }
    
    public void setVitaminC(String vitaminC) {
        this.vitaminC = vitaminC;
    }
    public String getVitaminB1() {
        return this.vitaminB1;
    }
    
    public void setVitaminB1(String vitaminB1) {
        this.vitaminB1 = vitaminB1;
    }
    public String getVitaminB2() {
        return this.vitaminB2;
    }
    
    public void setVitaminB2(String vitaminB2) {
        this.vitaminB2 = vitaminB2;
    }
    public String getVitaminPp() {
        return this.vitaminPp;
    }
    
    public void setVitaminPp(String vitaminPp) {
        this.vitaminPp = vitaminPp;
    }
    public String getVitaminB5() {
        return this.vitaminB5;
    }
    
    public void setVitaminB5(String vitaminB5) {
        this.vitaminB5 = vitaminB5;
    }
    public String getVitaminB6() {
        return this.vitaminB6;
    }
    
    public void setVitaminB6(String vitaminB6) {
        this.vitaminB6 = vitaminB6;
    }
    public String getFolat() {
        return this.folat;
    }
    
    public void setFolat(String folat) {
        this.folat = folat;
    }
    public String getVitaminB9() {
        return this.vitaminB9;
    }
    
    public void setVitaminB9(String vitaminB9) {
        this.vitaminB9 = vitaminB9;
    }
    public String getVitaminH() {
        return this.vitaminH;
    }
    
    public void setVitaminH(String vitaminH) {
        this.vitaminH = vitaminH;
    }
    public String getVitaminB12() {
        return this.vitaminB12;
    }
    
    public void setVitaminB12(String vitaminB12) {
        this.vitaminB12 = vitaminB12;
    }
    public String getVitaminA() {
        return this.vitaminA;
    }
    
    public void setVitaminA(String vitaminA) {
        this.vitaminA = vitaminA;
    }
    public String getVitaminD() {
        return this.vitaminD;
    }
    
    public void setVitaminD(String vitaminD) {
        this.vitaminD = vitaminD;
    }
    public String getVitaminE() {
        return this.vitaminE;
    }
    
    public void setVitaminE(String vitaminE) {
        this.vitaminE = vitaminE;
    }
    public String getVitaminK() {
        return this.vitaminK;
    }
    
    public void setVitaminK(String vitaminK) {
        this.vitaminK = vitaminK;
    }
    public String getBetaCaroten() {
        return this.betaCaroten;
    }
    
    public void setBetaCaroten(String betaCaroten) {
        this.betaCaroten = betaCaroten;
    }
    public String getAlphaCaroten() {
        return this.alphaCaroten;
    }
    
    public void setAlphaCaroten(String alphaCaroten) {
        this.alphaCaroten = alphaCaroten;
    }
    public String getBetaCryptoxanthin() {
        return this.betaCryptoxanthin;
    }
    
    public void setBetaCryptoxanthin(String betaCryptoxanthin) {
        this.betaCryptoxanthin = betaCryptoxanthin;
    }
    public String getLypcogen() {
        return this.lypcogen;
    }
    
    public void setLypcogen(String lypcogen) {
        this.lypcogen = lypcogen;
    }
    public String getLycopen() {
        return this.lycopen;
    }
    
    public void setLycopen(String lycopen) {
        this.lycopen = lycopen;
    }
    public String getLutein() {
        return this.lutein;
    }
    
    public void setLutein(String lutein) {
        this.lutein = lutein;
    }
    public String getPurin() {
        return this.purin;
    }
    
    public void setPurin(String purin) {
        this.purin = purin;
    }
    public String getTotalIsoflavone() {
        return this.totalIsoflavone;
    }
    
    public void setTotalIsoflavone(String totalIsoflavone) {
        this.totalIsoflavone = totalIsoflavone;
    }
    public String getTotalSFAcid() {
        return this.totalSFAcid;
    }
    
    public void setTotalSFAcid(String totalSFAcid) {
        this.totalSFAcid = totalSFAcid;
    }
    public String getTotalMFAcid() {
        return this.totalMFAcid;
    }
    
    public void setTotalMFAcid(String totalMFAcid) {
        this.totalMFAcid = totalMFAcid;
    }
    public String getTotalPFAcid() {
        return this.totalPFAcid;
    }
    
    public void setTotalPFAcid(String totalPFAcid) {
        this.totalPFAcid = totalPFAcid;
    }
    public String getTotalTFAcid() {
        return this.totalTFAcid;
    }
    
    public void setTotalTFAcid(String totalTFAcid) {
        this.totalTFAcid = totalTFAcid;
    }
    public Integer getCholesterol() {
        return this.cholesterol;
    }
    
    public void setCholesterol(Integer cholesterol) {
        this.cholesterol = cholesterol;
    }
    public Integer getPhytosterol() {
        return this.phytosterol;
    }
    
    public void setPhytosterol(Integer phytosterol) {
        this.phytosterol = phytosterol;
    }
    public Integer getLysin() {
        return this.lysin;
    }
    
    public void setLysin(Integer lysin) {
        this.lysin = lysin;
    }
    public Integer getMethionin() {
        return this.methionin;
    }
    
    public void setMethionin(Integer methionin) {
        this.methionin = methionin;
    }
    public Integer getTryptophan() {
        return this.tryptophan;
    }
    
    public void setTryptophan(Integer tryptophan) {
        this.tryptophan = tryptophan;
    }
    public Integer getPhenylalanin() {
        return this.phenylalanin;
    }
    
    public void setPhenylalanin(Integer phenylalanin) {
        this.phenylalanin = phenylalanin;
    }
    public Integer getThreonin() {
        return this.threonin;
    }
    
    public void setThreonin(Integer threonin) {
        this.threonin = threonin;
    }
    public Integer getValin() {
        return this.valin;
    }
    
    public void setValin(Integer valin) {
        this.valin = valin;
    }
    public Integer getLeucin() {
        return this.leucin;
    }
    
    public void setLeucin(Integer leucin) {
        this.leucin = leucin;
    }
    public Integer getIsoleucin() {
        return this.isoleucin;
    }
    
    public void setIsoleucin(Integer isoleucin) {
        this.isoleucin = isoleucin;
    }
    public Integer getArginin() {
        return this.arginin;
    }
    
    public void setArginin(Integer arginin) {
        this.arginin = arginin;
    }
    public Integer getHistidin() {
        return this.histidin;
    }
    
    public void setHistidin(Integer histidin) {
        this.histidin = histidin;
    }
    public Integer getCystin() {
        return this.cystin;
    }
    
    public void setCystin(Integer cystin) {
        this.cystin = cystin;
    }
    public Integer getTyrosin() {
        return this.tyrosin;
    }
    
    public void setTyrosin(Integer tyrosin) {
        this.tyrosin = tyrosin;
    }
    public Integer getAlanin() {
        return this.alanin;
    }
    
    public void setAlanin(Integer alanin) {
        this.alanin = alanin;
    }
    public Integer getAcidAspartic() {
        return this.acidAspartic;
    }
    
    public void setAcidAspartic(Integer acidAspartic) {
        this.acidAspartic = acidAspartic;
    }
    public Integer getAcidGlutamic() {
        return this.acidGlutamic;
    }
    
    public void setAcidGlutamic(Integer acidGlutamic) {
        this.acidGlutamic = acidGlutamic;
    }
    public Integer getGlycin() {
        return this.glycin;
    }
    
    public void setGlycin(Integer glycin) {
        this.glycin = glycin;
    }
    public Integer getProlin() {
        return this.prolin;
    }
    
    public void setProlin(Integer prolin) {
        this.prolin = prolin;
    }
    public Integer getSerin() {
        return this.serin;
    }
    
    public void setSerin(Integer serin) {
        this.serin = serin;
    }




}


